services:
  app:
    build:
      context: .
    image: cartesius:latest
    env_file: .env.production
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/cartesius_production
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      RAILS_LOG_TO_STDOUT: "1"
      RAILS_MAX_THREADS: 5
    ports:
      - "80:80"
    depends_on:
      - db
    restart: unless-stopped


  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cartesius_production
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data:
